steps:
  - name: 'openjdk:21-jdk-bullseye'
    id: 'deploy'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        ./gradlew --no-daemon :appengineDeploy

timeout: '1600s'
options:
  logging: CLOUD_LOGGING_ONLY
