name: CI with JaCoCo and SonarCloud

on:
  pull_request:
    branches:
      - main  # Adjust if your main branch has a different name

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch full history for SonarCloud PR analysis

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Grant Execute Permission for Gradlew
        run: chmod +x gradlew

      - name: Run Tests with JaCoCo
        run: ./gradlew test jacocoTestReport

      - name: Debug JaCoCo Report
        run: ls -lah build/reports/jacoco/test/

      - name: Run SonarCloud Analysis
        run: |
          ./gradlew sonar \
            -Dsonar.pullrequest.branch=${{ github.head_ref }} \
            -Dsonar.pullrequest.base=${{ github.base_ref }} \
            -Dsonar.pullrequest.key=${{ github.event.pull_request.number }}
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
